name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3964a974d8645a176408b58c025562403662ae5178469e230af30702d1288732"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
