name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11233e40c5238f11d858153404965523ade36410ae2c011bca507cbadd0f98fb"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
