name = "GregTech CEu Modern Community Pack Extended"
author = "Alice"
version = "1.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be3989511099e0c828eff649ebf9e146b96a02e34a60356fc466c13b12d1852f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
